apiVersion: v1
kind: Pod
metadata:
  name: flask-hello-world-pod
  labels:
    app: flask-hello-world
spec:
  containers:
    - name: flask-hello-world-container
      image: prabinkc/flask-hello-world
