apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000 # container is exposed to port 5000
      nodePort: 30500
  selector:
    app: hello-world
    type: front-end  
