apiVersion: apps/v1
kind: Deployment
metadata:
  name: shapetracker-mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      name: shapetracker-mysql-server
      labels:
        tier: data
    spec:
      containers:
        - name: shapetracker-mysql-server
          image: prabinkc/shapetracker-mysql-server

    